#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 25 15:35:17 2019

@author: tim
"""

import functions
test_recording_id = '156258'

#uncomment the function you want to test

#functions.test_create_all_necessary_folders()

# Before running test, copy recording 156258.mp4a into downloaded_recordings folder, and delete folder called test_moa    
#functions.test_create_tagged_recording()

#functions.test_get_cacophony_user_token()

#functions.test_get_token_for_retrieving_recording(test_recording_id)

#functions.test_get_recording_from_server(test_recording_id)



#functions.test_add_tag_to_recording()
#
#functions.test_get_audio_recordings_with_tags_information_from_server()

#functions.test_get_recording_information_for_a_single_recording()

#functions.test_extract_tags_for_single_audio_recording_from_single_recording_information()

#functions.test_extract_tags_from_recordings_with_tags()

#functions.test_extract_recordingIds_from_json_file_of_basic_recording_information()

#functions.test_get_full_recording_information_using_file_list_of_recordings()

#functions.test_extract_individual_tags_from_file_containing_list_of_recording_with_full_information()

#functions.test_extract_tags_for_single_audio_recording_from_single_recording_information()

#functions.test_download_recordings_that_have_a_tag()

#functions.test_create_recording_clips_based_on_tags()

#functions.test_convert_file_from_raw_to_librosa_array()

#functions.test_create_tagged_recording_as_wav()

#functions.test_add_information_to_csv_file()

#functions.test_create_tagged_recording_as_array()

#functions.test_get_recordings_for_device_information_from_server()

#functions.test_get_ids_of_recordings_to_download()

#functions.test_get_list_of_devices_for_group()

#functions.test_get_audio_recordings_with_tags_information_from_server()

#functions.test_plot_recording()

#functions.test_plot_all_recordings()

#functions.test_apply_low_and_high_pass_filter()

#functions.test_play_sound_file()

#functions.test_highpass_filter()

#functions.test_lowpass_filter()

#functions.test_apply_low_and_high_pass_filter()

#functions.create_filtered_files()

#functions.test_extract_clips_from_single_filtered_reocording()

#functions.extract_clips_from_all_filtered_recordings()

#functions.test_get_device_id_using_device_name()



#functions.test_FindSquawks_Tim()

#functions.test_add_tag_to_server()

#functions.test_get_recording_ids_for_device_name()

#functions.test_sort_into_day_or_night()

#functions.remove_cicada_noise()


#functions.test_extract_clips_from_folder_of_filtered_reocordings()













































